### ISSUE TITLE
SA2StageSelEdit: .ini Error

### ISSUE THREAD

**Issue by ElectroNuke** [X-Hax/sa_tools#179]
None of the readme files specify which .ini I should open in SA2StageSelEdit. Either way, I tried Stage Select.ini in the "advertise" folder in my project directory, but got a "sequence contains no matching element" error. When I tried opening advertise_data.ini, it froze and then showed an "object reference not set to an instance of an object" error. All I did was extract SA Tools to my documents library and created a new SA2 project, so this should not be happening.

P.S. Opening any e???.prs folder in SA2EventViewer just shows a black screen. I also can't imagine why this would be happening.

**Comment by PiKeyAr** [comment]
In the current version of SA Tools, SA2StageSelEdit opens a project (.sap) file that you create in SA Tools Hub.
To start playing scenes in SA2EventViewer, you need to click the Play button on the toolbar or hit P on the keyboard.
