### ISSUE TITLE
Support for XVM? And .Net download

### ISSUE THREAD

**Issue by SonikkuA-DatH** [X-Hax/sa_tools#206]
Could there be support for XVM textures? Phantasy Star Ep 1/2 Xbox and PSO Blue Burst uses them, and the texture format is documented partially here: https://github.com/bogglez/Ninja-Lib/blob/master/documentation/readme.md

A tool to import/export textures is noted, though has no documentation here (it's texture manager): https://psoskins.jimdofree.com/tools/

For the .Net warning, it should specify that x86 32bit .Net should be installed, not 64bit

**Comment by MainMemory** [comment]
We don't control the .NET warning, that's part of the library. Also, you do need the x64 .NET 5 Desktop runtime if you install the x64 version of SA Tools. What I think we should actually do is replace the main download with a little .NET 4.x program that asks you whether you want to install the x86 or x64 version and provides links to the relevant .NET 5 runtimes.

**Comment by Shadowth117** [comment]
I handled .xvms like this:
https://github.com/Shadowth117/PSO2-Aqua-Library/blob/53cdc8b94d9dce8755565bf5b801245a18b186ea/AquaModelLibrary/Extra/PSOXVMConvert.cs

The contained files are literally .dds with an .xvr header usually and internally the games that use it swap a .dds header in in loading anyways. There are some pixel formats I don't know the equivalent variant for, but this will work for most.

It is definitely an odd part of the Ninja era in the same family as the typical .pvm and .gvm stuff for pc and assumedly Xbox.

**Comment by Shadowth117** [comment]
This got added recently so this can be closed.
