### ISSUE TITLE
Unable to load Wild Canyon iSALVL

### ISSUE THREAD

**Issue by Omiyaru** [X-Hax/sa_tools#222]
im given this Error

Program: SALVL
Build Date: 06/26/2022 04:53:41
OS Version: Microsoft Windows NT 10.0.22000.0
Log:
----Loading a new level: Wild Canyon----
Loading textures: C:\Program Files (x86)\Steam\steamapps\common\Sonic Adventure 2\resource\gd_PC\SONICTEX.PRS
Loading textures: C:\Program Files (x86)\Steam\steamapps\common\Sonic Adventure 2\resource\gd_PC\TERIOSTEX.PRS
Loading textures: C:\Program Files (x86)\Steam\steamapps\common\Sonic Adventure 2\resource\gd_PC\KNUCKTEX.PRS
Loading textures: C:\Program Files (x86)\Steam\steamapps\common\Sonic Adventure 2\resource\gd_PC\ROUGETEX.PRS
Loading textures: C:\Program Files (x86)\Steam\steamapps\common\Sonic Adventure 2\resource\gd_PC\TWALKTEX.PRS
Loading textures: C:\Program Files (x86)\Steam\steamapps\common\Sonic Adventure 2\resource\gd_PC\EWALKTEX.PRS
Loading textures: C:\Program Files (x86)\Steam\steamapps\common\Sonic Adventure 2\resource\gd_PC\bgtex16.PRS
Loading textures: C:\Program Files (x86)\Steam\steamapps\common\Sonic Adventure 2\resource\gd_PC\E_G_KUMITEX.PRS
Loading textures: C:\Program Files (x86)\Steam\steamapps\common\Sonic Adventure 2\resource\gd_PC\E_EMITEX.PRS
Loading textures: C:\Program Files (x86)\Steam\steamapps\common\Sonic Adventure 2\resource\gd_PC\E_GOLDTEX.PRS
Loading textures: C:\Program Files (x86)\Steam\steamapps\common\Sonic Adventure 2\resource\gd_PC\E_KUMITEX.PRS
Loading textures: C:\Program Files (x86)\Steam\steamapps\common\Sonic Adventure 2\resource\gd_PC\E_KYOKOTEX.PRS
Loading textures: C:\Program Files (x86)\Steam\steamapps\common\Sonic Adventure 2\resource\gd_PC\E_AITEX.PRS
Loading textures: C:\Program Files (x86)\Steam\steamapps\common\Sonic Adventure 2\resource\gd_PC\levupdai_tmtex.PRS
Loading textures: C:\Program Files (x86)\Steam\steamapps\common\Sonic Adventure 2\resource\gd_PC\objtex_stg16.PRS
Loading textures: C:\Program Files (x86)\Steam\steamapps\common\Sonic Adventure 2\resource\gd_PC\efftex_common.PRS
Loading textures: C:\Program Files (x86)\Steam\steamapps\common\Sonic Adventure 2\resource\gd_PC\PRS\objtex_common.PAK
Loading textures: C:\Program Files (x86)\Steam\steamapps\common\Sonic Adventure 2\resource\gd_PC\stg16_wind.PRS
Loading textures: C:\Program Files (x86)\Steam\steamapps\common\Sonic Adventure 2\resource\gd_PC\LANDTX16.PRS
Loading textures: C:\Program Files (x86)\Steam\steamapps\common\Sonic Adventure 2\resource\gd_PC\landtx16.PRS
System.Exception: INI File error: Group "DMYOBJ" already exists.
line 308
 ---> System.ArgumentException: An item with the same key has already been added. Key: DMYOBJ
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at SplitTools.IniFile.Load(String[] data) in C:\Programs\sa_tools\Libraries\SplitTools\IniFile.cs:line 72
   --- End of inner exception stack trace ---
   at SplitTools.IniFile.Load(String[] data) in C:\Programs\sa_tools\Libraries\SplitTools\IniFile.cs:line 76
   at SAModel.SALVL.MainForm.MainLevelLoadLoop() in C:\Programs\sa_tools\SALVL\Loading.cs:line 1105

**Comment by ItsEasyActually** [comment]
Fixed in [84f8646](https://github.com/X-Hax/sa_tools/commit/84f8646a8fc6adb35f84e35b74d500fae41e36ce). 

You can copy the ini files in the SA Tools>GameConfig>PC_SA2>objdefs folder after updating and paste them to your objdefs folder in your project if you don't want to resplit the project.
