### ISSUE TITLE
Text missing from SADX Tweaker 2 

### ISSUE THREAD

**Issue by Hyperuranium** [X-Hax/sa_tools#25]
There are some types of text that aren't part of the cutscenes that aren't editable from SADX Tweaker 2 (and from no one other tool provided by SA Tools), such as some menu texts and [character unlocks messages](https://i.imgur.com/qlntNPd.png).

I found some hex addresses of the stuff that I am talking about:

Character unlocks messages: around 003E01B0 to 003E0530

Wind Stone, Ice Stone, etc messages: around around 003FBED0 to 003FC6F0 

Menu messages from Pause Menu: around 003DD040 fino a 003DD440

What also seems to be missing are texts about Big's lures and probabily other menu text, but I don't know where to exactly point out at the moment.

**Comment by AuroraWright** [comment]
Any news about this?

**Comment by PiKeyAr** [comment]
Support for individual and multi-language strings has been added to SA Tools and the Mod Loader. While SADXTweaker2 doesn't have UI to edit this data, it can be edited as text files in a mod project and exported with the SA Tools Hub as regular mod data.
