### ISSUE TITLE
Impossibility to decompile latest version of Sonic Adventure DX executable file

### ISSUE THREAD

**Issue by rveyrand** [X-Hax/sa_tools#254]
- [X] I am using the latest version of SA Tools.

- [X] The problem is consistently reproducible.

- [X] I have looked through the list of open issues and confirmed that the problem hasn't been reported before.

**Describe the bug/request**
Attempting to create a new mod project with the latest version of the game on steam will always result into a crash (log provided)

**To Reproduce (if applicable)**
1) rename the executable (from "Sonic Adventure DX.exe" to "sonic.exe")
2) load SA Tools and create a new project with Sonic Adventure as the base game

**Screenshots**
![Capture d'écran 2023-12-26 091734](https://github.com/X-Hax/sa_tools/assets/67048302/7954f82e-28b2-41cc-92f3-4d8a20a5fd7b)

**Files**
https://drive.google.com/file/d/1y4VB0M4sYNY92OBhw8Cfts7FBFnELwU9/view?usp=drive_link
(provided the executable file for conveniences)

**Log**
Program: SA Tools Hub
Build Date: 12/22/2023 06:15:06
OS Version: Microsoft Windows NT 10.0.22631.0
Log:
System.NullReferenceException: Object reference not set to an instance of an object.
   at SAToolsHub.newProj.BackgroundWorker1_RunWorkerCompleted(Object sender, RunWorkerCompletedEventArgs e) in C:\Programs\sa_tools\SAToolsHub\Forms\newProj.cs:line 632
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)

**Comment by Sewer56** [comment]
I haven't worked on this in any capacity, but based on your description, you're trying to throw SADX 2011 (Steam Version) into the tooling. The tooling is built around the 2004 US release of the game, and I doubt that'll change anytime soon.

**Comment by MainMemory** [comment]
FYI, you can convert your Steam copy into the 2004 version with the [SADX Mod Installer](https://sadxmodinstaller.unreliable.network/), then you can make and use mods with it.
