### ISSUE TITLE
SA1: Chao Editor: Evolution tab/section has lots of errors

### ISSUE THREAD

**Issue by TreeBranches** [X-Hax/sa_tools#256]
Before creating a new issue, please read the following:

This issue tracker is for bug reports and feature requests. This is not the place to ask how to use the tools or where to find models etc. If you need help using the tools, check out the wiki or ask on Discord.

In addition, please confirm the following:

- [X] I am using the latest version of SA Tools.

- [X] The problem is consistently reproducible.

- [X] I have looked through the list of open issues and confirmed that the problem hasn't been reported before.

**Describe the bug/request**
In the Evolution tab of the Chao Editor for SA1 DC:

- The graph/siders are back to front (Run/Power should be swapped, Fly/Swim should be swapped).
- The Skills section is largely mislabelled
- The tooltip for skill values is incorrect
- Changes to the Swim value does not apply

First an introduction to the Chao in-game:

![Chao](https://github.com/X-Hax/sa_tools/assets/8653544/467577a3-5976-442f-aa70-fb828fd1a2f3)

Each chao is clearly in their evolution stage matching their names, where they have only be 'fed' the animals matching their role.

I set all 4 chao to have a value of 999 for all stats (since the tooltip says the range is 0-999). Saved and loaded the game. I provided relevant animals to Punchy, Runny and Floaty, but none to Swimmy. I then noticed that none of the chaos were doing well in their races, so I loaded the editor again.

![EvolutionTab](https://github.com/X-Hax/sa_tools/assets/8653544/7cd6a0bf-59e1-4d3a-bc37-8f4538138ffe)

Based on what I've done in the game post-edit, you can spot the following mistakes;

- "Swimmy" is shown as being in the "Fly" evolution range on the graph, "Punchy" in "Run", "Runny" in "Power", and "Floaty" in "Swim"
- None of them have their Swim values in the Skills section set to 999 or higher; they were reset to their original values. Changing them to 999 and switching to another Chao, then back again, also resets the value (so the Swim value is not sticking).
- The Chaos I've given animals to have their values in the Skills section set to higher than 999, marking the suggested range as incorrect.
- The "Fly" and "Run" values in the Skills section are mislabelled. "Runny" has a "Fly" value of 1655 despite being given "Speed" animals and no "Fly" animals, and "Floaty" has a "Run" value of 1367 despite being given "Fly" animals with no "Speed" animals. "Power" appears to be correct, so I assume "Swim" is correct too (as I did not give it any animals in this instance).

Edited as the issue was submitted accidentally before ready.

**Comment by PiKeyAr** [comment]
Thanks for the report.

> The graph/siders are back to front (Run/Power should be swapped, Fly/Swim should be swapped).

Fixed.

> Changes to the Swim value does not apply

Fixed.

> The Skills section is largely mislabelled

"Largely"? If this is about the Fly and Run stats being swapped, apparently there's been an error in Chao data documentation all these years (though I should've looked at the official struct anyway). I've compared the same Chao in SA1 Chao Adventure and Tyro's VMU Chao Editor (Chao Adventure on the left). Anyway, this should be fixed now.
![image](https://github.com/X-Hax/sa_tools/assets/23312549/224a229b-e590-4c2c-8f7b-f744ea58c8bb)

> The Chaos I've given animals to have their values in the Skills section set to higher than 999, marking the suggested range as incorrect.

The range is correct. The editor displays an additional decimal piece (hence it says "multiplied by 10") that isn't shown in Chao Adventure but is used in calculations, so when you want to put in 999 you should actually put in 9990.

**Comment by PiKeyAr** [comment]
Closing for now, please reopen if unresolved.
