### ISSUE TITLE
NPC Message Editor not saving changes

### ISSUE THREAD

**Issue by dqf318** [X-Hax/sa_tools#258]
Before creating a new issue, please read the following:

This issue tracker is for bug reports and feature requests. This is not the place to ask how to use the tools or where to find models etc. If you need help using the tools, check out the wiki or ask on Discord.

In addition, please confirm the following:

- [X] I am using the latest version of SA Tools.

- [X] The problem is consistently reproducible.

- [X] I have looked through the list of open issues and confirmed that the problem hasn't been reported before.

**Describe the bug/request**
For some reason, when I change something using the NPC Message Editor, and then save and quit, the changes are not saved at all.

**To Reproduce (if applicable)**
1. Change any message in the NPC Message Editor.
2. Save and quit the NPC Message Editor.
3. Reopen the NPC Message Editor.

**Expected behavior**
The changes to the NPC Message Editor should remain, even when you close out of the program after saving.

**Screenshots**

**Files**
If the program crashes during work with a specific file (such as a custom level), attach it to this report.

**Log**
If the program crashed with a bug report dialog, please paste the contents of the report here.

**Additional context**

**Comment by Sora-yx** [comment]
That should be fixed with the last update

**Comment by dqf318** [comment]
> That should be fixed with the last update

Yep, it’s all good now!
