### ISSUE TITLE
Remove the reliance on x86/x64

### ISSUE THREAD

**Issue by IsaacMarovitz** [X-Hax/sa_tools#273]
As far as I can tell, the only reason for enforcing x86-only is the reliance on `SACompGC` as an external DLL. I would be more than happy to rewrite this in C# which would remove the need to Marshal calls to it and only allow x86.

**Comment by PiKeyAr** [comment]
Sorry, why do you think SA Tools are x86 only? There are x64 binaries available for download, and the SACompGC library comes in x86 and x64 variations... Anyway if you want to rewrite it in C#, here's the source code: https://github.com/X-Hax/SACompGC

**Comment by IsaacMarovitz** [comment]
> Sorry, why do you think SA Tools are x86 only?

I mean x86/x86_64, should've clarified. The reason why I'm interested is together with #274, SA Tools could support my platform (ARM64 macOS)
