### ISSUE TITLE
Not configuring one of the games' paths assumes hard drive root

### ISSUE THREAD

**Issue by MsHinchy** [X-Hax/sa_tools#35]
When I configured SADX's folder and not SA2's, the subfolders of my totally unrelated Projects directory **in the root of the hard drive** show up in the Project Manager as SA2 projects. Telling it where my copy of SA2 was located fixed it, but this could be a problem for people who only own one of the two games or only have one installed.

**Comment by PiKeyAr** [comment]
I get this pop-up twice when I don't configure the path for SA2 (I don't have SA2):
![image](https://user-images.githubusercontent.com/23312549/53677582-a6868a80-3cf5-11e9-89b6-6380ba45ee3b.png)
Not a big deal, but I think this pop-up is unnecessary. Especially for people who don't mod SA2.
