### ISSUE TITLE
Support for splitting individual strings

### ISSUE THREAD

**Issue by PiKeyAr** [X-Hax/sa_tools#95]
I've been trying to add several items to `splitsadx.ini` (particularly the stuff mentioned in #25), but I'm unable to because SA Tools currently doesn't seem to support splitting individual strings or string lists. Using the `stringarray` category doesn't work for string pointer arrays (such as the character unlock message list at `0x516968`/`0x916968`. Judging by other `stringarray` items in the INI that do work, I think it's because the tool expects a zero after each string in these arrays. `masterstringlist` added recently for SA2 doesn't seem to work either.
I guess a new category is necessary for these strings to work?

**Comment by MainMemory** [comment]
I think the problem with the unlock messages is that they're all different languages. We'd have to invent a new data type specifically for that use case. I can also add support for splitting individual strings.

**Comment by PiKeyAr** [comment]
Implemented both single and multi language strings.
